server:
  port: 8190

# 服务节点,要求分布式下每个节点不同
node: 01

spring:
  dubbo:
    application:
      name: yeepay-service
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
    scan: org.yeepay.service.impl
  profiles:
     active: prod

logging:
  file: ./log/yeepay-service.log
  level:
    org.yeepay.service.dao.mapper: debug